drop table if exists comments;
drop table if exists photo_details;
drop table if exists photo;
drop table if exists photoblog_user_role;
drop table if exists photoblog_users;

create table photoblog_users (
    username varchar(255) not null,
    email varchar(255),
    user_password varchar(255),
    phone_number bigint,
    user_description varchar(255),
    primary key (username)
);

create table photoblog_user_role (
    user_role_id integer generated by default as identity,
    user_role varchar(255) not null,
    username varchar(255) not null,
    primary key (user_role_id),
    foreign key (username) references photoblog_users
);

create table photo (
    photo_id integer generated by default as identity,
    photo_data blob,
    photo_file_type varchar(255),
    photo_filename varchar(255),
    photo_uploaded_datetime timestamp(6),
    upload_uname varchar(255),
    primary key (photo_id)
);

create table photo_details (
    photo_details_id integer generated by default as identity,
    photo_description varchar(255),
    photo_id integer,
    photo_title varchar(255),
    primary key (photo_details_id),
    foreign key (photo_id) references photo
);

create table comments (
    comment_id bigint generated by default as identity,
    comment_datetime timestamp(6),
    comment_text varchar(255),
    photo_id integer,
    username varchar(255),
    primary key (comment_id),
    foreign key (photo_id) references photo
);

